### ISSUE TITLE
How to run locally to test and develop

### ISSUE THREAD

**Issue by tiagostutz** [jsenv/jsenv-file-size-impact#30]
Hi there!

I tried to add json-file-size-impact to my project but it was not working because it was yielding to an infinite loop that crashed the JSVM (of course). The thing is, my repo has a structure that is a bit different from the provided examples here. My tests are here: https://github.com/tiagostutz/stop-analyzing-embed/pull/5

That being said, I'd like to know how can I ran this jsenv-file-size-impact locally because after several attempts I couldn't go through. Currently, I tried something like this: 

```
GITHUB_EVENT_NAME=pull_request GITHUB_TOKEN=<my_token> GITHUB_REPOSITORY=tiagostutz/stop-analyzing-embed GITHUB_REF=refs/pull/5/ GITHUB_WORKSPACE= node ./.github/workflows/file-size-impact/report-file-size-impact.js
```

But didn't work. I received this message:
```
Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
creating comment

```

Could you give me some light here on how to run locally the solution (MY OS is MacOS)?

**Comment by tiagostutz** [comment]
I could make it work by setting `GITHUB_WORKSPACE` with the project absolute path, like: `GITHUB_WORKSPACE=file:////Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed`

The thing is that the process was not finding the directory and was crashing, but the error message is not friendly. I discovered debugging around.

One importante thing is to prefix the directory path with `file:////` using 4 slashes.
